name = "hbd70-leaderboard"
main = "index.js"
compatibility_date = "2026-09-01"
workers_dev = true

routes = [
  { pattern = "api.al.lusk.win", custom_domain = true }
]

# Cloudflare D1 Serverless SQLite Database Binding
[[d1_databases]]
binding = "DB"
database_name = "hbd70-leaderboard"
database_id = "96383718-7adb-4173-9d33-32b0c9a8b114"

